services:
  - type: web
    name: goat-bot
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg python3 python3-pip
      pip3 install -U yt-dlp
      npm install
    startCommand: node index.js
